service: ${self:custom.team}-${self:custom.product}-${self:custom.service}

package:
  exclude:
    - '*/*.md'
    - '*/.webpack/**'

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  stage: staging
  cfLogs: true
  region: eu-west-1
  tracing: true
  logRetentionInDays: 7
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  tags:
    business: ${self:custom.business}
    team: ${self:custom.team}
    product: ${self:custom.product}
    project: ${self:custom.service}
    environment: ${self:custom.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  webpack: ./lambda/webpack.config.js
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:custom.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true
    endpointType: 'regional'
  # Webpack
  bundle:
    dev: dev
    staging: prod
    prod: prod
  webpackIncludeModules: true
  # General
  awsAccount: ${env:AWS_ACCOUNT}
  awsAccountId: ${env:AWS_ACCOUNT_ID}
  business: ${env:BUSINESS}
  team: ${env:TEAM}
  product: ${env:PRODUCT}
  service: ${env:SERVICE}

functions:
  main:
    handler: lambda/index.handler
    events:
    - http:
        path: /
        method: get
    - http:
        path: "{proxy+}"
        method: get
